[package]
name = "solstice_daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.41", features = ["derive"] }
pbkdf2 = { version = "0.12.2", features = ["simple"] }
portable-pty = { git = "https://github.com/tuxuser/wezterm", branch = "spawn_command_as_user" }
rand_core = { version = "0.6.4", features = ["std"] }
russh = { version = "0.53", default-features = false, features = ["flate2", "ring"] }
russh-sftp = "2.1.1"
tokio = { version = "1.38", features = ["full"] }
tracing = "0.1.40"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = [
    "local-time",
    "time",
    "env-filter",
] }
winapi = { version = "0.3.9", default-features = false, features = ["handleapi"] }

windows = { version = "0.58.0", features = [
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_NetworkManagement_WindowsFirewall",

    # For impersonation
    "Win32_System_LibraryLoader",

    # For WFP
    "Win32_Security",
    "Win32_NetworkManagement_WindowsFilteringPlatform",
    "Win32_System_Rpc",
] }

[target.'cfg(windows)'.dependencies]
winreg = "0.52"

[features]
default = []
firewall = []
