// Bindings generated by `windows-bindgen` 0.58.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]
pub mod Xbox {
    pub mod System {
        pub mod Internal {
            pub mod Power {
                windows_core::imp::define_interface!(
                    IPowerPropertiesStatics,
                    IPowerPropertiesStatics_Vtbl,
                    0xc434745e_17fd_4a13_94c9_997e2dd41e64
                );
                impl windows_core::RuntimeType for IPowerPropertiesStatics {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::for_interface::<Self>();
                }
                #[repr(C)]
                pub struct IPowerPropertiesStatics_Vtbl {
                    pub base__: windows_core::IInspectable_Vtbl,
                    pub AllowAutoSystemUpdate: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut bool,
                    )
                        -> windows_core::HRESULT,
                    pub SetAllowAutoSystemUpdate:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            bool,
                        ) -> windows_core::HRESULT,
                    pub AllowInstantOn: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut bool,
                    )
                        -> windows_core::HRESULT,
                    pub SetAllowInstantOn: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        bool,
                    )
                        -> windows_core::HRESULT,
                    pub WakeXboxOnVoice: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut bool,
                    )
                        -> windows_core::HRESULT,
                    pub SetWakeXboxOnVoice: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        bool,
                    )
                        -> windows_core::HRESULT,
                    pub SystemIdleTimeout: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut u32,
                    )
                        -> windows_core::HRESULT,
                    pub SetSystemIdleTimeout: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        u32,
                    )
                        -> windows_core::HRESULT,
                    pub ShutDownConsole:
                        unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
                    pub SleepConsole:
                        unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
                    pub RestartConsole:
                        unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
                    pub FastGameResume: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut bool,
                    )
                        -> windows_core::HRESULT,
                    pub SetFastGameResume: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        bool,
                    )
                        -> windows_core::HRESULT,
                    pub ExternalStorageSelectiveSuspend:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            *mut bool,
                        ) -> windows_core::HRESULT,
                    pub SetExternalStorageSelectiveSuspend:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            bool,
                        ) -> windows_core::HRESULT,
                    pub InstantOnTitleID: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut u32,
                    )
                        -> windows_core::HRESULT,
                    pub SetInstantOnTitleID: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        u32,
                    )
                        -> windows_core::HRESULT,
                    pub PowerChime: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut PowerChimeMode,
                    )
                        -> windows_core::HRESULT,
                    pub SetPowerChime: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        PowerChimeMode,
                    )
                        -> windows_core::HRESULT,
                    pub AllowAutoContentUpdates: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut bool,
                    )
                        -> windows_core::HRESULT,
                    pub SetAllowAutoContentUpdates:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            bool,
                        ) -> windows_core::HRESULT,
                    pub PromptEnableAutoUpdates: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut bool,
                    )
                        -> windows_core::HRESULT,
                    pub SetPromptEnableAutoUpdates:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            bool,
                        ) -> windows_core::HRESULT,
                    pub Allow4KAssetDownloads: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut bool,
                    )
                        -> windows_core::HRESULT,
                    pub SetAllow4KAssetDownloads:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            bool,
                        ) -> windows_core::HRESULT,
                    pub AllowRemoteInstall: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut bool,
                    )
                        -> windows_core::HRESULT,
                    pub SetAllowRemoteInstall: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        bool,
                    )
                        -> windows_core::HRESULT,
                    pub AllowRemoteManagement: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut bool,
                    )
                        -> windows_core::HRESULT,
                    pub SetAllowRemoteManagement:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            bool,
                        ) -> windows_core::HRESULT,
                    pub NotifyHomeReady:
                        unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
                    pub SystemForceIdleTimeout: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut u32,
                    )
                        -> windows_core::HRESULT,
                    pub SetSystemForceIdleTimeout:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            u32,
                        ) -> windows_core::HRESULT,
                    pub DisableBootAnimationAudio:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            *mut bool,
                        ) -> windows_core::HRESULT,
                    pub SetDisableBootAnimationAudio:
                        unsafe extern "system" fn(
                            *mut core::ffi::c_void,
                            bool,
                        ) -> windows_core::HRESULT,
                    pub CarbonAwareRsPlus: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut bool,
                    )
                        -> windows_core::HRESULT,
                    pub ActiveHourMode: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut AdjustedActiveHourMode,
                    )
                        -> windows_core::HRESULT,
                    pub SetActiveHourMode: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        AdjustedActiveHourMode,
                    )
                        -> windows_core::HRESULT,
                    pub ActiveHourStart: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut u32,
                    )
                        -> windows_core::HRESULT,
                    pub SetActiveHourStart: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        u32,
                    )
                        -> windows_core::HRESULT,
                    pub ActiveHourEnd: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        *mut u32,
                    )
                        -> windows_core::HRESULT,
                    pub SetActiveHourEnd: unsafe extern "system" fn(
                        *mut core::ffi::c_void,
                        u32,
                    )
                        -> windows_core::HRESULT,
                    pub StartGipEnrollMode:
                        unsafe extern "system" fn(*mut core::ffi::c_void) -> windows_core::HRESULT,
                }
                pub struct PowerProperties;
                impl PowerProperties {
                    pub fn AllowAutoSystemUpdate() -> windows_core::Result<bool> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).AllowAutoSystemUpdate)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetAllowAutoSystemUpdate(value: bool) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetAllowAutoSystemUpdate)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn AllowInstantOn() -> windows_core::Result<bool> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).AllowInstantOn)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetAllowInstantOn(value: bool) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetAllowInstantOn)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn WakeXboxOnVoice() -> windows_core::Result<bool> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).WakeXboxOnVoice)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetWakeXboxOnVoice(value: bool) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetWakeXboxOnVoice)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn SystemIdleTimeout() -> windows_core::Result<u32> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).SystemIdleTimeout)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetSystemIdleTimeout(value: u32) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetSystemIdleTimeout)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn ShutDownConsole() -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).ShutDownConsole)(
                                windows_core::Interface::as_raw(this),
                            )
                            .ok()
                        })
                    }
                    pub fn SleepConsole() -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SleepConsole)(
                                windows_core::Interface::as_raw(this),
                            )
                            .ok()
                        })
                    }
                    pub fn RestartConsole() -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).RestartConsole)(
                                windows_core::Interface::as_raw(this),
                            )
                            .ok()
                        })
                    }
                    pub fn FastGameResume() -> windows_core::Result<bool> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).FastGameResume)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetFastGameResume(value: bool) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetFastGameResume)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn ExternalStorageSelectiveSuspend() -> windows_core::Result<bool> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).ExternalStorageSelectiveSuspend)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetExternalStorageSelectiveSuspend(
                        value: bool,
                    ) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this)
                                .SetExternalStorageSelectiveSuspend)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn InstantOnTitleID() -> windows_core::Result<u32> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).InstantOnTitleID)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetInstantOnTitleID(value: u32) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetInstantOnTitleID)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn PowerChime() -> windows_core::Result<PowerChimeMode> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).PowerChime)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetPowerChime(value: PowerChimeMode) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetPowerChime)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn AllowAutoContentUpdates() -> windows_core::Result<bool> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).AllowAutoContentUpdates)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetAllowAutoContentUpdates(value: bool) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetAllowAutoContentUpdates)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn PromptEnableAutoUpdates() -> windows_core::Result<bool> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).PromptEnableAutoUpdates)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetPromptEnableAutoUpdates(value: bool) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetPromptEnableAutoUpdates)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn Allow4KAssetDownloads() -> windows_core::Result<bool> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).Allow4KAssetDownloads)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetAllow4KAssetDownloads(value: bool) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetAllow4KAssetDownloads)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn AllowRemoteInstall() -> windows_core::Result<bool> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).AllowRemoteInstall)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetAllowRemoteInstall(value: bool) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetAllowRemoteInstall)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn AllowRemoteManagement() -> windows_core::Result<bool> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).AllowRemoteManagement)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetAllowRemoteManagement(value: bool) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetAllowRemoteManagement)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn NotifyHomeReady() -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).NotifyHomeReady)(
                                windows_core::Interface::as_raw(this),
                            )
                            .ok()
                        })
                    }
                    pub fn SystemForceIdleTimeout() -> windows_core::Result<u32> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).SystemForceIdleTimeout)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetSystemForceIdleTimeout(value: u32) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetSystemForceIdleTimeout)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn DisableBootAnimationAudio() -> windows_core::Result<bool> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).DisableBootAnimationAudio)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetDisableBootAnimationAudio(value: bool) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetDisableBootAnimationAudio)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn CarbonAwareRsPlus() -> windows_core::Result<bool> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).CarbonAwareRsPlus)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn ActiveHourMode() -> windows_core::Result<AdjustedActiveHourMode> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).ActiveHourMode)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetActiveHourMode(
                        value: AdjustedActiveHourMode,
                    ) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetActiveHourMode)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn ActiveHourStart() -> windows_core::Result<u32> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).ActiveHourStart)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetActiveHourStart(value: u32) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetActiveHourStart)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn ActiveHourEnd() -> windows_core::Result<u32> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            let mut result__ = core::mem::zeroed();
                            (windows_core::Interface::vtable(this).ActiveHourEnd)(
                                windows_core::Interface::as_raw(this),
                                &mut result__,
                            )
                            .map(|| result__)
                        })
                    }
                    pub fn SetActiveHourEnd(value: u32) -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).SetActiveHourEnd)(
                                windows_core::Interface::as_raw(this),
                                value,
                            )
                            .ok()
                        })
                    }
                    pub fn StartGipEnrollMode() -> windows_core::Result<()> {
                        Self::IPowerPropertiesStatics(|this| unsafe {
                            (windows_core::Interface::vtable(this).StartGipEnrollMode)(
                                windows_core::Interface::as_raw(this),
                            )
                            .ok()
                        })
                    }
                    #[doc(hidden)]
                    pub fn IPowerPropertiesStatics<
                        R,
                        F: FnOnce(&IPowerPropertiesStatics) -> windows_core::Result<R>,
                    >(
                        callback: F,
                    ) -> windows_core::Result<R> {
                        static SHARED: windows_core::imp::FactoryCache<
                            PowerProperties,
                            IPowerPropertiesStatics,
                        > = windows_core::imp::FactoryCache::new();
                        SHARED.call(callback)
                    }
                }
                impl windows_core::RuntimeName for PowerProperties {
                    const NAME: &'static str = "Windows.Xbox.System.Internal.Power.PowerProperties";
                }
                #[repr(transparent)]
                #[derive(PartialEq, Eq, Copy, Clone, Default)]
                pub struct AdjustedActiveHourMode(pub i32);
                impl AdjustedActiveHourMode {
                    pub const Automatic: Self = Self(0i32);
                    pub const Manual: Self = Self(1i32);
                    pub const AlwaysActive: Self = Self(2i32);
                }
                impl windows_core::TypeKind for AdjustedActiveHourMode {
                    type TypeKind = windows_core::CopyType;
                }
                impl core::fmt::Debug for AdjustedActiveHourMode {
                    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                        f.debug_tuple("AdjustedActiveHourMode")
                            .field(&self.0)
                            .finish()
                    }
                }
                impl windows_core::RuntimeType for AdjustedActiveHourMode {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::from_slice(
                            b"enum(Windows.Xbox.System.Internal.Power.AdjustedActiveHourMode;i4)",
                        );
                }
                #[repr(transparent)]
                #[derive(PartialEq, Eq, Copy, Clone, Default)]
                pub struct PowerChimeMode(pub i32);
                impl PowerChimeMode {
                    pub const On: Self = Self(0i32);
                    pub const OnlyPowerButtonAndVoice: Self = Self(1i32);
                    pub const Off: Self = Self(2i32);
                }
                impl windows_core::TypeKind for PowerChimeMode {
                    type TypeKind = windows_core::CopyType;
                }
                impl core::fmt::Debug for PowerChimeMode {
                    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                        f.debug_tuple("PowerChimeMode").field(&self.0).finish()
                    }
                }
                impl windows_core::RuntimeType for PowerChimeMode {
                    const SIGNATURE: windows_core::imp::ConstBuffer =
                        windows_core::imp::ConstBuffer::from_slice(
                            b"enum(Windows.Xbox.System.Internal.Power.PowerChimeMode;i4)",
                        );
                }
                pub trait IPowerPropertiesStatics_Impl: Sized {
                    fn AllowAutoSystemUpdate(&self) -> windows_core::Result<bool>;
                    fn SetAllowAutoSystemUpdate(&self, value: bool) -> windows_core::Result<()>;
                    fn AllowInstantOn(&self) -> windows_core::Result<bool>;
                    fn SetAllowInstantOn(&self, value: bool) -> windows_core::Result<()>;
                    fn WakeXboxOnVoice(&self) -> windows_core::Result<bool>;
                    fn SetWakeXboxOnVoice(&self, value: bool) -> windows_core::Result<()>;
                    fn SystemIdleTimeout(&self) -> windows_core::Result<u32>;
                    fn SetSystemIdleTimeout(&self, value: u32) -> windows_core::Result<()>;
                    fn ShutDownConsole(&self) -> windows_core::Result<()>;
                    fn SleepConsole(&self) -> windows_core::Result<()>;
                    fn RestartConsole(&self) -> windows_core::Result<()>;
                    fn FastGameResume(&self) -> windows_core::Result<bool>;
                    fn SetFastGameResume(&self, value: bool) -> windows_core::Result<()>;
                    fn ExternalStorageSelectiveSuspend(&self) -> windows_core::Result<bool>;
                    fn SetExternalStorageSelectiveSuspend(
                        &self,
                        value: bool,
                    ) -> windows_core::Result<()>;
                    fn InstantOnTitleID(&self) -> windows_core::Result<u32>;
                    fn SetInstantOnTitleID(&self, value: u32) -> windows_core::Result<()>;
                    fn PowerChime(&self) -> windows_core::Result<PowerChimeMode>;
                    fn SetPowerChime(&self, value: PowerChimeMode) -> windows_core::Result<()>;
                    fn AllowAutoContentUpdates(&self) -> windows_core::Result<bool>;
                    fn SetAllowAutoContentUpdates(&self, value: bool) -> windows_core::Result<()>;
                    fn PromptEnableAutoUpdates(&self) -> windows_core::Result<bool>;
                    fn SetPromptEnableAutoUpdates(&self, value: bool) -> windows_core::Result<()>;
                    fn Allow4KAssetDownloads(&self) -> windows_core::Result<bool>;
                    fn SetAllow4KAssetDownloads(&self, value: bool) -> windows_core::Result<()>;
                    fn AllowRemoteInstall(&self) -> windows_core::Result<bool>;
                    fn SetAllowRemoteInstall(&self, value: bool) -> windows_core::Result<()>;
                    fn AllowRemoteManagement(&self) -> windows_core::Result<bool>;
                    fn SetAllowRemoteManagement(&self, value: bool) -> windows_core::Result<()>;
                    fn NotifyHomeReady(&self) -> windows_core::Result<()>;
                    fn SystemForceIdleTimeout(&self) -> windows_core::Result<u32>;
                    fn SetSystemForceIdleTimeout(&self, value: u32) -> windows_core::Result<()>;
                    fn DisableBootAnimationAudio(&self) -> windows_core::Result<bool>;
                    fn SetDisableBootAnimationAudio(&self, value: bool)
                        -> windows_core::Result<()>;
                    fn CarbonAwareRsPlus(&self) -> windows_core::Result<bool>;
                    fn ActiveHourMode(&self) -> windows_core::Result<AdjustedActiveHourMode>;
                    fn SetActiveHourMode(
                        &self,
                        value: AdjustedActiveHourMode,
                    ) -> windows_core::Result<()>;
                    fn ActiveHourStart(&self) -> windows_core::Result<u32>;
                    fn SetActiveHourStart(&self, value: u32) -> windows_core::Result<()>;
                    fn ActiveHourEnd(&self) -> windows_core::Result<u32>;
                    fn SetActiveHourEnd(&self, value: u32) -> windows_core::Result<()>;
                    fn StartGipEnrollMode(&self) -> windows_core::Result<()>;
                }
                impl windows_core::RuntimeName for IPowerPropertiesStatics {
                    const NAME: &'static str =
                        "Windows.Xbox.System.Internal.Power.IPowerPropertiesStatics";
                }
                impl IPowerPropertiesStatics_Vtbl {
                    pub const fn new<Identity: windows_core::IUnknownImpl, const OFFSET: isize>(
                    ) -> IPowerPropertiesStatics_Vtbl
                    where
                        Identity: IPowerPropertiesStatics_Impl,
                    {
                        unsafe extern "system" fn AllowAutoSystemUpdate<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::AllowAutoSystemUpdate(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetAllowAutoSystemUpdate<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetAllowAutoSystemUpdate(this, value)
                                .into()
                        }
                        unsafe extern "system" fn AllowInstantOn<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::AllowInstantOn(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetAllowInstantOn<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetAllowInstantOn(this, value).into()
                        }
                        unsafe extern "system" fn WakeXboxOnVoice<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::WakeXboxOnVoice(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetWakeXboxOnVoice<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetWakeXboxOnVoice(this, value).into()
                        }
                        unsafe extern "system" fn SystemIdleTimeout<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut u32,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::SystemIdleTimeout(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetSystemIdleTimeout<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: u32,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetSystemIdleTimeout(this, value).into()
                        }
                        unsafe extern "system" fn ShutDownConsole<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::ShutDownConsole(this).into()
                        }
                        unsafe extern "system" fn SleepConsole<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SleepConsole(this).into()
                        }
                        unsafe extern "system" fn RestartConsole<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::RestartConsole(this).into()
                        }
                        unsafe extern "system" fn FastGameResume<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::FastGameResume(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetFastGameResume<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetFastGameResume(this, value).into()
                        }
                        unsafe extern "system" fn ExternalStorageSelectiveSuspend<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::ExternalStorageSelectiveSuspend(
                                this,
                            ) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetExternalStorageSelectiveSuspend<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetExternalStorageSelectiveSuspend(
                                this, value,
                            )
                            .into()
                        }
                        unsafe extern "system" fn InstantOnTitleID<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut u32,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::InstantOnTitleID(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetInstantOnTitleID<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: u32,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetInstantOnTitleID(this, value).into()
                        }
                        unsafe extern "system" fn PowerChime<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut PowerChimeMode,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::PowerChime(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetPowerChime<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: PowerChimeMode,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetPowerChime(this, value).into()
                        }
                        unsafe extern "system" fn AllowAutoContentUpdates<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::AllowAutoContentUpdates(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetAllowAutoContentUpdates<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetAllowAutoContentUpdates(this, value)
                                .into()
                        }
                        unsafe extern "system" fn PromptEnableAutoUpdates<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::PromptEnableAutoUpdates(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetPromptEnableAutoUpdates<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetPromptEnableAutoUpdates(this, value)
                                .into()
                        }
                        unsafe extern "system" fn Allow4KAssetDownloads<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::Allow4KAssetDownloads(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetAllow4KAssetDownloads<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetAllow4KAssetDownloads(this, value)
                                .into()
                        }
                        unsafe extern "system" fn AllowRemoteInstall<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::AllowRemoteInstall(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetAllowRemoteInstall<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetAllowRemoteInstall(this, value).into()
                        }
                        unsafe extern "system" fn AllowRemoteManagement<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::AllowRemoteManagement(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetAllowRemoteManagement<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetAllowRemoteManagement(this, value)
                                .into()
                        }
                        unsafe extern "system" fn NotifyHomeReady<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::NotifyHomeReady(this).into()
                        }
                        unsafe extern "system" fn SystemForceIdleTimeout<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut u32,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::SystemForceIdleTimeout(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetSystemForceIdleTimeout<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: u32,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetSystemForceIdleTimeout(this, value)
                                .into()
                        }
                        unsafe extern "system" fn DisableBootAnimationAudio<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::DisableBootAnimationAudio(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetDisableBootAnimationAudio<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetDisableBootAnimationAudio(this, value)
                                .into()
                        }
                        unsafe extern "system" fn CarbonAwareRsPlus<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut bool,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::CarbonAwareRsPlus(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn ActiveHourMode<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut AdjustedActiveHourMode,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::ActiveHourMode(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetActiveHourMode<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: AdjustedActiveHourMode,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetActiveHourMode(this, value).into()
                        }
                        unsafe extern "system" fn ActiveHourStart<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut u32,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::ActiveHourStart(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetActiveHourStart<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: u32,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetActiveHourStart(this, value).into()
                        }
                        unsafe extern "system" fn ActiveHourEnd<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            result__: *mut u32,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            match IPowerPropertiesStatics_Impl::ActiveHourEnd(this) {
                                Ok(ok__) => {
                                    result__.write(core::mem::transmute_copy(&ok__));
                                    windows_core::HRESULT(0)
                                }
                                Err(err) => err.into(),
                            }
                        }
                        unsafe extern "system" fn SetActiveHourEnd<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                            value: u32,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::SetActiveHourEnd(this, value).into()
                        }
                        unsafe extern "system" fn StartGipEnrollMode<
                            Identity: windows_core::IUnknownImpl,
                            const OFFSET: isize,
                        >(
                            this: *mut core::ffi::c_void,
                        ) -> windows_core::HRESULT
                        where
                            Identity: IPowerPropertiesStatics_Impl,
                        {
                            let this: &Identity =
                                &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                            IPowerPropertiesStatics_Impl::StartGipEnrollMode(this).into()
                        }
                        Self {
                            base__: windows_core::IInspectable_Vtbl::new::<
                                Identity,
                                IPowerPropertiesStatics,
                                OFFSET,
                            >(),
                            AllowAutoSystemUpdate: AllowAutoSystemUpdate::<Identity, OFFSET>,
                            SetAllowAutoSystemUpdate: SetAllowAutoSystemUpdate::<Identity, OFFSET>,
                            AllowInstantOn: AllowInstantOn::<Identity, OFFSET>,
                            SetAllowInstantOn: SetAllowInstantOn::<Identity, OFFSET>,
                            WakeXboxOnVoice: WakeXboxOnVoice::<Identity, OFFSET>,
                            SetWakeXboxOnVoice: SetWakeXboxOnVoice::<Identity, OFFSET>,
                            SystemIdleTimeout: SystemIdleTimeout::<Identity, OFFSET>,
                            SetSystemIdleTimeout: SetSystemIdleTimeout::<Identity, OFFSET>,
                            ShutDownConsole: ShutDownConsole::<Identity, OFFSET>,
                            SleepConsole: SleepConsole::<Identity, OFFSET>,
                            RestartConsole: RestartConsole::<Identity, OFFSET>,
                            FastGameResume: FastGameResume::<Identity, OFFSET>,
                            SetFastGameResume: SetFastGameResume::<Identity, OFFSET>,
                            ExternalStorageSelectiveSuspend: ExternalStorageSelectiveSuspend::<
                                Identity,
                                OFFSET,
                            >,
                            SetExternalStorageSelectiveSuspend: SetExternalStorageSelectiveSuspend::<
                                Identity,
                                OFFSET,
                            >,
                            InstantOnTitleID: InstantOnTitleID::<Identity, OFFSET>,
                            SetInstantOnTitleID: SetInstantOnTitleID::<Identity, OFFSET>,
                            PowerChime: PowerChime::<Identity, OFFSET>,
                            SetPowerChime: SetPowerChime::<Identity, OFFSET>,
                            AllowAutoContentUpdates: AllowAutoContentUpdates::<Identity, OFFSET>,
                            SetAllowAutoContentUpdates: SetAllowAutoContentUpdates::<
                                Identity,
                                OFFSET,
                            >,
                            PromptEnableAutoUpdates: PromptEnableAutoUpdates::<Identity, OFFSET>,
                            SetPromptEnableAutoUpdates: SetPromptEnableAutoUpdates::<
                                Identity,
                                OFFSET,
                            >,
                            Allow4KAssetDownloads: Allow4KAssetDownloads::<Identity, OFFSET>,
                            SetAllow4KAssetDownloads: SetAllow4KAssetDownloads::<Identity, OFFSET>,
                            AllowRemoteInstall: AllowRemoteInstall::<Identity, OFFSET>,
                            SetAllowRemoteInstall: SetAllowRemoteInstall::<Identity, OFFSET>,
                            AllowRemoteManagement: AllowRemoteManagement::<Identity, OFFSET>,
                            SetAllowRemoteManagement: SetAllowRemoteManagement::<Identity, OFFSET>,
                            NotifyHomeReady: NotifyHomeReady::<Identity, OFFSET>,
                            SystemForceIdleTimeout: SystemForceIdleTimeout::<Identity, OFFSET>,
                            SetSystemForceIdleTimeout: SetSystemForceIdleTimeout::<Identity, OFFSET>,
                            DisableBootAnimationAudio: DisableBootAnimationAudio::<Identity, OFFSET>,
                            SetDisableBootAnimationAudio: SetDisableBootAnimationAudio::<
                                Identity,
                                OFFSET,
                            >,
                            CarbonAwareRsPlus: CarbonAwareRsPlus::<Identity, OFFSET>,
                            ActiveHourMode: ActiveHourMode::<Identity, OFFSET>,
                            SetActiveHourMode: SetActiveHourMode::<Identity, OFFSET>,
                            ActiveHourStart: ActiveHourStart::<Identity, OFFSET>,
                            SetActiveHourStart: SetActiveHourStart::<Identity, OFFSET>,
                            ActiveHourEnd: ActiveHourEnd::<Identity, OFFSET>,
                            SetActiveHourEnd: SetActiveHourEnd::<Identity, OFFSET>,
                            StartGipEnrollMode: StartGipEnrollMode::<Identity, OFFSET>,
                        }
                    }
                    pub fn matches(iid: &windows_core::GUID) -> bool {
                        iid == &<IPowerPropertiesStatics as windows_core::Interface>::IID
                    }
                }
            }
        }
    }
}
