[package]
name = "test_program"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.21", optional = true }
win_dbg_logger = { version = "0.1", optional = true }

[features]
default = ["dep:log", "dep:win_dbg_logger"]
debug = []
