[package]
name = "shellcode_utils"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.num]
version = "0.4"
default-features = false

[dependencies.num-traits]
version = "0.2"
default-features = false
